### ISSUE TITLE
Runtime fails when loading dapr grpc on fincm3 from Alpine build

### ISSUE THREAD

**Issue by kb2ma** [balena-io-playground/cloudBlock#44]
The main cloud block runtime fails when loading the dapr grpc package on fincm3 (armv7). The error is shown below. This error started to occur after merge of #41 to use an Alpine-python-build image to generate files for an Alpine-python-run image. The error does not occur with amd64 or arm64 builds.

I did find a similar issue in the grpc project that was resolved, but it included the discouraging [comment](https://github.com/grpc/grpc/issues/25386#issuecomment-776814261):

> Building and running in python alpine arm images has always posed issues with grpcio.

```
Traceback (most recent call last):
12.05.21 08:08:03 (-0400)  cloud    File "./src/main.py", line 6, in <module>
12.05.21 08:08:03 (-0400)  cloud      from dapr.ext.grpc import App, BindingRequest
12.05.21 08:08:03 (-0400)  cloud    File "/root/.local/lib/python3.8/site-packages/dapr/ext/grpc/__init__.py", line 8, in <module>
12.05.21 08:08:03 (-0400)  cloud      from dapr.clients.grpc._request import InvokeMethodRequest, BindingRequest
12.05.21 08:08:03 (-0400)  cloud    File "/root/.local/lib/python3.8/site-packages/dapr/clients/__init__.py", line 12, in <module>
12.05.21 08:08:03 (-0400)  cloud      from dapr.clients.grpc.client import DaprGrpcClient, MetadataTuple, InvokeMethodResponse
12.05.21 08:08:03 (-0400)  cloud    File "/root/.local/lib/python3.8/site-packages/dapr/clients/grpc/client.py", line 11, in <module>
12.05.21 08:08:03 (-0400)  cloud      import grpc  # type: ignore
12.05.21 08:08:03 (-0400)  cloud    File "/root/.local/lib/python3.8/site-packages/grpc/__init__.py", line 23, in <module>
12.05.21 08:08:03 (-0400)  cloud      from grpc._cython import cygrpc as _cygrpc
12.05.21 08:08:03 (-0400)  cloud  ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /root/.local/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-arm-linux-gnueabihf.so)
```

I tried adding the `libc6-compat` package when running `install_packages` in the Dockerfile because that package contains `ld-linux-armhf.so.3`. The error then changes to:

```
[Logs]    [5/12/2021, 9:56:11 AM] [cloud] ImportError: Error relocating /root/.local/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-arm-linux-gnueabihf.so: __xstat: symbol not found
```

**Comment by kb2ma** [comment]
Confirmed the issue still occurs as of 2021-06-03.

**Comment by kb2ma** [comment]
Try using @rahul-thakoor's approach in Dashboard, as seen in [Dockerfile](https://github.com/balenablocks/dashboard/blob/master/Dockerfile.template). Copy in required Debian Python packages to a Busybox base image to avoid use of Alpine.
